### PR TITLE
#19 rename term 'Location' to 'Locator' were appropriate for consistency

### PR DESCRIPTION
**Pull request by krispenner**
Sorry for the delay, this is my first pull request and also my first commit to GitHub.
Let me know if I am missing anything, I don't know what else might be expected as part of a pull request.

### CODE REVIEW

**Comment by ENikS** [comment]
I would suggest adding these, not renaming it. A lot of software is based on these names and if I merge it as is it will brake a lot of code and make many people unhappy.

**Comment by ENikS** [comment]
Actually, after thinking about it for a while I see this change doing more harm than good. Sorry for the confusion but I have to decline this.

**Comment by krispenner** [comment]
The title is maybe a bit misleading.  I actually added the IsLocatorProviderSet property and marked the replaced IsLocationProviderSet property as obsolete.  I do not believe that this would break anything dependent on this code.  The unit tests should not matter that the name space was also renamed to be consistent.

**Comment by ENikS** [comment]
I understand but this library been used like this since 2008. There is really no good reason to modify it in any way. 

The change you are proposing does not bring any value other than syntactic sugar which compiler will strip down anyway.

If you really want to help with the library there are few issues with help wanted labels. Documentation and samples are two other areas where I need help...

**Comment by krispenner** [comment]
Understood, I consider code readability such as consistent naming a very good value to add, there is no syntactic sugar there, but this was just my suggestion for code improvement.  Not a problem either way!

**Pull request closed without merging**
