### PR TITLE
Added support to .NET Standard 1.0

### PR DESCRIPTION
**Pull request by vitaliy-leschenko**
Added support to .NET Standard 1.0

### CODE REVIEW

**Comment by ENikS** [comment]
You may as well update service locator too so I can release them both.

**Comment by vitaliy-leschenko** [comment]
Yes, I will make Pull Request for Unity.ServiceLocator now.

**Comment by ENikS** [comment]
Thank you for the help! 

There are plenty more things to do if you have time...

**Comment by vitaliy-leschenko** [comment]
Unity.ServiceLocator needed to increase version too

**Comment by ENikS** [comment]
I did to [2.1.0](https://www.nuget.org/packages/Unity.ServiceLocation/)

**Pull request merged**
